<?php

/**
 * @file
 * Provides helper functions and hooks for the comm100 module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function comm100_page_attachments_alter(array &$page) {

  $config = \Drupal::config('comm100.settings');

  $path = \Drupal::service('path.current')->getPath();

  if (empty($config->get('site_id')) || empty($config->get('plan_id'))) {
    return;
  }

  $is_admin_page = TRUE;
  if (!_comm100_active($path)) {
    $is_admin_page = FALSE;
  }

  $js_settings = [
    'site_id'  => $config->get('site_id'),
    'plan_id' => $config->get('plan_id'),
    'plan_type' => $config->get('plan_type'),
    'main_chatserver_domain' => $config->get('main_chatserver_domain'),
    'standby_chatserver_domain' => $config->get('standby_chatserver_domain'),
    'is_admin_page'    => $is_admin_page,
  ];

  $page['#attached']['drupalSettings']['comm100'] = $js_settings;

  $page['#attached']['library'][] = 'comm100/comm100';

}

/**
 * Provides a status function to determine if the library should be added.
 *
 * This tests of the current page is an admin url, if so, it will not load the
 * library.
 *
 * @param string $path
 *   The current request path.
 *
 * @return bool
 *   True if the library should be loaded. False otherwise.
 */
function _comm100_active($path) {

  $page_match = FALSE;

  if (strpos($path, "admin")) {
    $page_match = TRUE;
  }

  return $page_match;
}

/**
 * Implements hook_theme().
 */
function comm100_theme($existing, $type, $theme, $path) {
  return [
    'comm100_settings' => [
      'variables' => [],
    ],
  ];
}
