# Schema for the configuration files of the stickynav module.
stickynav.settings.*:
  type: config_object
  label: 'Sticky Nav settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    selector:
      type: string
      label: 'jQuery Element Selector'
    offset:
      type: string
      label: 'Offset Selector'
    custom_offset:
      type: integer
      label: 'Custom Offset'
    roles:
      type: sequence
      label: 'Stickynav Roles'