<?php

/**
 * @file
 * The module file for dxpr_builder_media.
 */

/**
 * Implements hook_preprocess_views_view().
 */
function dxpr_builder_media_preprocess_views_view(&$variables) {
  if ($variables['view']->id() === 'dxpr_builder_media') {
    $variables['view_array']['#attached']['library'][] = 'dxpr_builder_media/view';
  }
}

/**
 * Implements hook_library_info_alter().
 */
function dxpr_builder_media_library_info_alter(&$libraries, $extension) {
  if ($extension === 'dxpr_builder_media' && isset($libraries['view'])) {
    /** @var \Drupal\Core\Asset\LibraryDiscoveryInterface $library_discovery */
    $library_discovery = \Drupal::service('library.discovery');

    $core_underscore = $library_discovery->getLibraryByName('core', 'underscore');
    $core_backbone = $library_discovery->getLibraryByName('core', 'backbone');

    $libs = [
      "view",
    ];

    foreach ($libs as $lib) {
      if ($core_underscore) {
        $libraries[$lib]['dependencies'][] = 'core/underscore';
      }
      else {
        $libraries[$lib]['dependencies'][] = 'dxpr_builder/underscore';
      }

      if ($core_backbone) {
        $libraries[$lib]['dependencies'][] = 'core/backbone';
      }
      else {
        // @todo Replace with dxpr_builder/backbone library.
        $libraries[$lib]['dependencies'][] = 'core/internal.backbone';
      }
    }
  }
}
